services:
  mongodb:
    image: mongo:7
    container_name: greetings-mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-root}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-greetings}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
